import { filterItems, formatDuration, safeImport } from "./lib/model.js";
import { deleteItem, getLibrary, getSettings, mergeImported, saveItem, saveLibrary, saveSettings, toggleFavorite } from "./lib/storage.js";
import { getCatalog } from "./lib/catalog.js";
import { getGuides } from "./lib/guides.js";
import { recordEvent } from "./lib/telemetry.js";
import { applyShieldView, getShieldState, toggleShield } from "./lib/shield.js";
import { clearThumbnails, deleteThumbnail } from "./lib/thumbnails.js";

const state={items:[],query:"",type:"all",site:"",performer:"",favorites:false,sort:"newest",view:"library",settings:{discreetMode:false,blurPreviews:false},programs:[],guides:[]};
const byId=(id)=>document.getElementById(id); const grid=byId("library-grid"); const empty=byId("empty-state"); const dialog=byId("item-dialog"); const form=byId("item-form"); const guideDialog=byId("guide-dialog");
let toastTimer,catalogLoaded=false,guidesLoaded=false,initialized=false;const posterObjectUrls=new Map();

function textElement(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;element.textContent=text;return element;}
function typeLabel(type){return{chat:"Character",image:"Image",video:"Video",voice:"Voice",link:"Link"}[type]||"Link";}
function cardDetails(item){const duration=formatDuration(item.durationSeconds);if(item.type==="video"||item.quality||duration)return [item.quality||"Quality —",duration||"Length —"].join(" · ");return typeLabel(item.type);}
function isEmbedPage(url){try{return /\/(?:embed|embedplayer|player)(?:\/|$)/i.test(new URL(url).pathname)}catch{return true}}
function showToast(message){const toast=byId("toast");toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},2600);}

function fillLibrarySelect(id,emptyLabel,values,selected){const select=byId(id);const unique=[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"en",{sensitivity:"base"}));const first=document.createElement("option");first.value="";first.textContent=emptyLabel;select.replaceChildren(first,...unique.map((value)=>{const option=document.createElement("option");option.value=value;option.textContent=value;return option}));select.value=unique.includes(selected)?selected:"";return select.value}
function renderLibraryFilters(){state.site=fillLibrarySelect("site-filter","All websites",state.items.map((item)=>item.source),state.site);state.performer=fillLibrarySelect("performer-filter","All performers",state.items.flatMap((item)=>item.actors||[]),state.performer)}
function performerButtons(item){const container=textElement("div","card-performers","");for(const name of item.actors||[]){const button=textElement("button","performer-filter-button",name);button.type="button";button.dataset.performerFilter=name;button.title=`Show videos with ${name}`;container.append(button)}return container}
async function attachRemotePoster(item,cover,poster,onReady){
  if(!item.thumbnailUrl)return;
  try{
    const response=await fetch(item.thumbnailUrl,{cache:"no-store",credentials:"include",referrer:item.url,referrerPolicy:"strict-origin-when-cross-origin"});
    if(!response.ok||Number(response.headers.get("content-length")||0)>12*1024*1024)throw new Error("Poster unavailable");
    const blob=await response.blob();if(blob.size>12*1024*1024||blob.type&&!blob.type.startsWith("image/"))throw new Error("Invalid poster");
    if(!cover.isConnected)return;
    const previous=posterObjectUrls.get(item.id);if(previous)URL.revokeObjectURL(previous);
    const objectUrl=URL.createObjectURL(blob);posterObjectUrls.set(item.id,objectUrl);poster.hidden=false;poster.src=objectUrl;onReady?.(objectUrl);
  }catch{poster.hidden=true;cover.classList.remove("has-media")}
}

function renderCard(item){
  const card=document.createElement("article");card.className="library-card";card.dataset.id=item.id;
  const cover=textElement("div",`card-cover type-${item.type}${state.settings.blurPreviews?" media-blurred":""}`,"");
  const poster=document.createElement("img");poster.className="card-media card-poster";poster.alt="";poster.loading="lazy";poster.decoding="async";poster.referrerPolicy="no-referrer";poster.hidden=true;
  poster.addEventListener("load",()=>{poster.hidden=false;cover.classList.add("has-media")});
  poster.addEventListener("error",()=>{poster.hidden=true;poster.removeAttribute("src");cover.classList.remove("has-media")});
  cover.append(poster);
  let preview=null,posterObjectUrl="";
  if(item.previewUrl&&!isEmbedPage(item.previewUrl)){
    const destroyPreview=()=>{if(!preview)return;preview.pause();preview.removeAttribute("src");preview.load();preview.remove();preview=null;cover.classList.remove("preview-playing")};
    const ensurePreview=()=>{if(preview)return preview;preview=document.createElement("video");preview.className="card-media card-preview";preview.src=item.previewUrl;preview.poster=posterObjectUrl;preview.preload="metadata";preview.muted=true;preview.loop=true;preview.playsInline=true;preview.setAttribute("aria-hidden","true");preview.setAttribute("referrerpolicy","no-referrer");preview.addEventListener("playing",()=>{cover.classList.add("has-media","preview-playing")});preview.addEventListener("error",destroyPreview,{once:true});cover.prepend(preview);return preview};
    const stop=()=>destroyPreview();
    const play=()=>{if(cover.classList.contains("media-blurred"))return;const media=ensurePreview();media.play().then(()=>cover.classList.add("preview-playing")).catch(stop)};
    card.addEventListener("mouseenter",play);card.addEventListener("mouseleave",stop);card.addEventListener("focusin",play);card.addEventListener("focusout",stop);
  }
  attachRemotePoster(item,cover,poster,(url)=>{posterObjectUrl=url;if(preview)preview.poster=url});
  if(item.type==="video"){
    const play=textElement("a","card-play","▶");play.href=item.url;play.target="_blank";play.rel="noreferrer";play.setAttribute("aria-label",`Open and play ${item.title}`);cover.append(play);
  }
  cover.append(textElement("span","card-type",typeLabel(item.type)));
  const favorite=textElement("button",`favorite-button${item.favorite?" active":""}`,item.favorite?"♥":"♡");favorite.type="button";favorite.dataset.action="favorite";favorite.setAttribute("aria-label",item.favorite?`Remove ${item.title} from favorites`:`Add ${item.title} to favorites`);cover.append(favorite);
  const body=textElement("div","card-body","");const meta=textElement("div","card-meta","");const source=textElement("button","card-source","");source.type="button";source.dataset.siteFilter=item.source;source.title=`Show items from ${item.source}`;if(item.siteIconUrl){const icon=document.createElement("img");icon.className="site-icon";icon.src=item.siteIconUrl;icon.alt="";icon.loading="lazy";icon.referrerPolicy="no-referrer";icon.addEventListener("error",()=>icon.remove());source.append(icon)}source.append(textElement("span","",item.source));meta.append(source,textElement("span","card-media-details",cardDetails(item)));const heading=textElement("h2","",item.title);heading.title=item.title;const description=item.type==="video"?(item.actors?.length?performerButtons(item):null):textElement("p","",item.note||"No private note added.");const tags=textElement("div","tags","");(item.tags||[]).slice(0,4).forEach((tag)=>tags.append(textElement("span","tag",`#${tag}`)));const actions=textElement("div","card-actions","");const open=textElement("a","open-link","Open ↗");open.href=item.url;open.target="_blank";open.rel="noreferrer";const edit=textElement("button","edit-button","Edit");edit.type="button";edit.dataset.action="edit";actions.append(open,edit);body.append(meta,heading);if(description)body.append(description);body.append(tags,actions);card.append(cover,body);return card;
}

function renderLibrary(){posterObjectUrls.forEach((url)=>URL.revokeObjectURL(url));posterObjectUrls.clear();renderLibraryFilters();const visible=filterItems(state.items,state);byId("library-count").textContent=String(state.items.length);grid.classList.toggle("discreet",Boolean(state.settings.discreetMode));grid.replaceChildren(...visible.map(renderCard));empty.hidden=visible.length>0;grid.hidden=visible.length===0;const heading=empty.querySelector("h2"),copy=empty.querySelector("p:not(.eyebrow)");if(!visible.length&&state.items.length){heading.textContent="No matches found.";copy.textContent="Try a different search or choose another filter.";byId("empty-add").hidden=true}else{heading.textContent="Nothing saved here yet.";copy.textContent="Open the PrivateFlix toolbar button on any page to save it, or add a link manually.";byId("empty-add").hidden=false}}
function openDialog(item=null){form.reset();byId("item-id").value=item?.id||"";byId("item-url").value=item?.url||"";byId("item-title").value=item?.title||"";byId("item-type").value=item?.type||"link";byId("item-tags").value=(item?.tags||[]).join(", ");byId("item-note").value=item?.note||"";byId("dialog-eyebrow").textContent=item?"EDIT SAVED ITEM":"ADD TO LIBRARY";byId("dialog-title").textContent=item?"Edit your save":"Save a link";byId("delete-item").hidden=!item;dialog.showModal();setTimeout(()=>byId("item-url").focus(),0);}

function setNavMenu(open){const toggle=byId("nav-menu-toggle"),menu=byId("secondary-nav");toggle.setAttribute("aria-expanded",String(open));menu.hidden=!open;toggle.classList.toggle("open",open)}
function switchView(view){state.view=view;document.querySelectorAll(".view").forEach((section)=>section.classList.toggle("active",section.id===`${view}-view`));document.querySelectorAll(".nav-item[data-view]").forEach((button)=>button.classList.toggle("active",button.dataset.view===view));byId("nav-menu-toggle").classList.toggle("active",["guides","settings","privacy"].includes(view));setNavMenu(false);location.hash=view;if(view==="discover"&&!catalogLoaded)loadCatalog();if(view==="guides"&&!guidesLoaded)loadGuides();document.querySelector(`#${view}-view h1`)?.focus?.({preventScroll:true});}

function catalogCard(program){const card=textElement("article",`catalog-card${program.featured?" featured":""}`,"");const cover=textElement("div","catalog-cover",String(program.name||"AI").slice(0,2).toUpperCase());if(program.imageUrl){const image=document.createElement("img");image.src=program.imageUrl;image.alt="";image.loading="lazy";image.referrerPolicy="no-referrer";cover.replaceChildren(image);}const body=textElement("div","catalog-body","");body.append(textElement("h2","",program.name||"AI platform"),textElement("p","",program.description||"Explore this adult AI creation platform."));const tags=textElement("div","catalog-tags","");(program.brands||[]).slice(0,4).forEach((tag)=>tags.append(textElement("span","",tag)));body.append(tags);const link=textElement("a","affiliate-cta",program.cta||"Explore platform ↗");link.href=program.affiliateUrl;link.target="_blank";link.rel="noreferrer sponsored";link.addEventListener("click",()=>recordEvent("affiliate_click",program.id));body.append(link,textElement("small","affiliate-note","Affiliate link · 18+"));card.append(cover,body);return card;}
function renderCatalog(){byId("catalog-grid").replaceChildren(...state.programs.map(catalogCard));}
async function loadCatalog(){const status=byId("catalog-status");status.hidden=false;status.textContent="Loading AI recommendations…";try{const{catalog,cached}=await getCatalog();state.programs=catalog.programs.filter((program)=>program.category==="ai"&&program.status==="open"&&program.affiliateUrl);renderCatalog();status.textContent=cached?"Showing the latest saved AI recommendations while offline.":`${state.programs.length} approved AI recommendation${state.programs.length===1?"":"s"}`;catalogLoaded=true}catch{status.textContent="AI recommendations are unavailable right now. Your private library still works normally.";}}

function guideCard(guide){const card=textElement("article","guide-card","");const cover=textElement("div","guide-cover","PF");if(guide.coverUrl){const image=document.createElement("img");image.src=guide.coverUrl;image.alt="";image.loading="lazy";image.referrerPolicy="no-referrer";cover.replaceChildren(image)}const body=textElement("div","guide-body","");body.append(textElement("h2","",guide.title),textElement("p","",guide.summary));const button=textElement("button","guide-open","Open how-to");button.type="button";button.dataset.guideId=guide.id;body.append(button);card.append(cover,body);return card;}
function renderGuides(){byId("guides-grid").replaceChildren(...state.guides.map(guideCard));}
async function loadGuides(){const status=byId("guides-status");try{const{data,cached}=await getGuides();state.guides=data.guides;renderGuides();status.textContent=cached?"Showing saved how-to guides while offline.":`${state.guides.length} how-to guide${state.guides.length===1?"":"s"} from the PrivateFlix feed`;guidesLoaded=true}catch{status.textContent="How-to guides are unavailable right now.";}}
function openGuide(guide){byId("guide-title").textContent=guide.title;byId("guide-summary").textContent=guide.summary;const content=byId("guide-content");content.replaceChildren(...guide.sections.map((item)=>{const section=document.createElement("section");section.append(textElement("h3","",item.heading),textElement("p","",item.body));return section}));const recommendation=byId("guide-recommendation");const program=state.programs.find((item)=>item.id===guide.affiliateProgramId);recommendation.replaceChildren();recommendation.hidden=!program;if(program){recommendation.append(textElement("strong","",`Recommended tool: ${program.name}`),textElement("span","","This optional recommendation contains an affiliate link."));const link=textElement("a","affiliate-cta",program.cta||"Explore platform ↗");link.href=program.affiliateUrl;link.target="_blank";link.rel="noreferrer sponsored";link.addEventListener("click",()=>recordEvent("affiliate_click",program.id));recommendation.append(link)}recordEvent("guide_open",guide.id);guideDialog.showModal();}

function exportLibrary(){const payload=JSON.stringify({version:1,exportedAt:new Date().toISOString(),items:state.items},null,2);const url=URL.createObjectURL(new Blob([payload],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`privateflix-library-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("Library exported.");}

async function refreshAllMedia(){
  const button=byId("refresh-media"),status=byId("media-refresh-status");
  if(!state.items.length){showToast("Add or import library items first.");return}
  button.disabled=true;button.textContent="Requesting access…";status.textContent="Waiting for website access…";
  try{
    const granted=await chrome.permissions.request({origins:["http://*/*","https://*/*"]});
    if(!granted){status.textContent="Website access was not granted. Your library was not changed.";showToast("Media refresh cancelled.");return}
    button.textContent="Refreshing…";status.textContent=`Preparing to refresh ${state.items.length} saved item${state.items.length===1?"":"s"}…`;
    const result=await chrome.runtime.sendMessage({type:"REFRESH_LIBRARY_MEDIA"});
    if(!result?.ok)throw new Error(result?.error||"Media refresh could not finish.");
    state.items=await getLibrary();renderLibrary();
    status.textContent=`Finished: ${result.postersFound} poster URLs · ${result.previewsFound} previews · ${result.detailsUpdated} details · ${result.unavailable} unavailable.`;
    showToast(result.updated?`Media updated for ${result.updated} item${result.updated===1?"":"s"}.`:"No new media was available. Try opening the source pages while signed in.");
  }catch(error){status.textContent=error instanceof Error?error.message:"Media refresh could not finish.";showToast("Could not refresh library media.")}
  finally{button.disabled=false;button.textContent="Refresh all media"}
}

document.querySelectorAll(".nav-item[data-view]").forEach((button)=>button.addEventListener("click",()=>switchView(button.dataset.view)));byId("nav-menu-toggle").addEventListener("click",(event)=>{event.stopPropagation();setNavMenu(byId("nav-menu-toggle").getAttribute("aria-expanded")!=="true")});document.addEventListener("click",(event)=>{if(!event.target.closest(".nav-menu"))setNavMenu(false)});document.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&byId("nav-menu-toggle").getAttribute("aria-expanded")==="true"){setNavMenu(false);byId("nav-menu-toggle").focus()}});document.querySelector('[data-view-link="library"]').addEventListener("click",(event)=>{event.preventDefault();switchView("library")});document.querySelectorAll("#add-item,#empty-add").forEach((button)=>button.addEventListener("click",()=>openDialog()));byId("close-dialog").addEventListener("click",()=>dialog.close());byId("cancel-dialog").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",(event)=>{if(event.target===dialog)dialog.close()});byId("close-guide").addEventListener("click",()=>guideDialog.close());guideDialog.addEventListener("click",(event)=>{if(event.target===guideDialog)guideDialog.close()});
byId("search").addEventListener("input",(event)=>{state.query=event.target.value;renderLibrary()});byId("sort").addEventListener("change",(event)=>{state.sort=event.target.value;renderLibrary()});byId("site-filter").addEventListener("change",(event)=>{state.site=event.target.value;renderLibrary()});byId("performer-filter").addEventListener("change",(event)=>{state.performer=event.target.value;renderLibrary()});document.querySelectorAll(".filter").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach((item)=>item.classList.toggle("active",item===button));state.favorites=button.dataset.filter==="favorites";state.type=["all","favorites"].includes(button.dataset.filter)?"all":button.dataset.filter;renderLibrary()}));
grid.addEventListener("click",async(event)=>{const performer=event.target.closest("button[data-performer-filter]");if(performer){state.performer=state.performer===performer.dataset.performerFilter?"":performer.dataset.performerFilter;renderLibrary();return}const site=event.target.closest("button[data-site-filter]");if(site){state.site=state.site===site.dataset.siteFilter?"":site.dataset.siteFilter;renderLibrary();return}const button=event.target.closest("button[data-action]");if(!button)return;const item=state.items.find((entry)=>entry.id===button.closest(".library-card")?.dataset.id);if(!item)return;if(button.dataset.action==="edit")openDialog(item);if(button.dataset.action==="favorite"){await toggleFavorite(item.id);state.items=await getLibrary();renderLibrary()}});
byId("guides-grid").addEventListener("click",async(event)=>{const button=event.target.closest("button[data-guide-id]");if(!button)return;if(!catalogLoaded)await loadCatalog();const guide=state.guides.find((item)=>item.id===button.dataset.guideId);if(guide)openGuide(guide)});
form.addEventListener("submit",async(event)=>{event.preventDefault();try{const existing=state.items.find((item)=>item.id===byId("item-id").value);await saveItem({...existing,id:byId("item-id").value||undefined,url:byId("item-url").value,title:byId("item-title").value,type:byId("item-type").value,tags:byId("item-tags").value,note:byId("item-note").value,favorite:existing?.favorite});state.items=await getLibrary();dialog.close();renderLibrary();showToast("Saved to your private library.")}catch(error){showToast(error instanceof Error?error.message:"Could not save this item.")}});
byId("delete-item").addEventListener("click",async()=>{const id=byId("item-id").value;const item=state.items.find((entry)=>entry.id===id);if(!item||!confirm(`Delete “${item.title}” from this browser?`))return;await Promise.all([deleteItem(id),deleteThumbnail(id)]);state.items=await getLibrary();dialog.close();renderLibrary();showToast("Saved item deleted.")});
byId("export-library").addEventListener("click",exportLibrary);byId("import-library").addEventListener("click",()=>byId("import-file").click());byId("import-file").addEventListener("change",async(event)=>{const file=event.target.files?.[0];if(!file)return;try{const imported=safeImport(JSON.parse(await file.text()));state.items=await mergeImported(imported);renderLibrary();byId("media-refresh-status").textContent="Backup imported. Use Refresh all media to fetch current poster URLs and previews.";showToast(`${imported.length} items imported.`)}catch(error){showToast(error instanceof Error?error.message:"Could not import this file.")}finally{event.target.value=""}});byId("refresh-media").addEventListener("click",refreshAllMedia);
byId("discreet-mode").addEventListener("change",async(event)=>{state.settings=await saveSettings({...state.settings,discreetMode:event.target.checked});renderLibrary()});byId("blur-previews").addEventListener("change",async(event)=>{state.settings=await saveSettings({...state.settings,blurPreviews:event.target.checked});renderLibrary()});
byId("clear-library").addEventListener("click",async()=>{if(!state.items.length)return showToast("Your library is already empty.");if(!confirm("Permanently clear your entire local PrivateFlix library?"))return;[state.items]=await Promise.all([saveLibrary([]),clearThumbnails()]);renderLibrary();showToast("Local library and thumbnails cleared.")});
chrome.storage.onChanged.addListener(async(changes,area)=>{if(area==="local"&&changes.privateflix_library_v1){state.items=await getLibrary();renderLibrary()}if(area==="session"&&changes.privateflix_privacy_shield)showShield(Boolean(changes.privateflix_privacy_shield.newValue))});chrome.runtime.onMessage.addListener((message)=>{if(message?.type!=="MEDIA_REFRESH_PROGRESS")return;const status=byId("media-refresh-status");status.textContent=`Refreshing ${message.current} of ${message.total}: ${message.title||"Saved item"}`});

async function initialize(){[state.items,state.settings]=await Promise.all([getLibrary(),getSettings()]);byId("discreet-mode").checked=Boolean(state.settings.discreetMode);byId("blur-previews").checked=Boolean(state.settings.blurPreviews);renderLibrary();const requested=location.hash.replace("#","");if(["library","discover","guides","settings","privacy"].includes(requested))switchView(requested);}
async function showShield(active){applyShieldView(active,{privateTitle:"My Library — PrivateFlix"});const app=byId("privateflix-app");app.inert=active;app.setAttribute("aria-hidden",String(active));if(active){dialog.close();guideDialog.close();grid.replaceChildren();byId("catalog-grid").replaceChildren();byId("guides-grid").replaceChildren();return}if(!initialized){initialized=true;await initialize()}else{renderLibrary();if(catalogLoaded)renderCatalog();if(guidesLoaded)renderGuides();}}
byId("shield-button").addEventListener("click",async()=>showShield(await toggleShield()));document.querySelectorAll("[data-restore-privateflix]").forEach((button)=>button.addEventListener("click",async()=>showShield(await toggleShield())));chrome.runtime.onMessage.addListener((message)=>{if(message?.type==="PRIVACY_SHIELD_CHANGED")showShield(Boolean(message.active))});
getShieldState().then(showShield).catch(()=>showShield(false)).catch(()=>showToast("PrivateFlix could not load local storage."));
